---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 30 seconds for target connection to become reachable/usable."
      # Your code here
      # Infrastructure phase
      # Backend stack is assured to be running in deployment phgase to get its URL. 30seconds are enough.
      shell: sleep 30

    - name: "install python for Ansible."
      # Your code here
      # Deploy phase
      become: yes
      apt:
        name: python
        state: latest

  roles:
    # Your code here
    # Infrastructure phase
    - configure-server
    # Monitoring phase
    - configure-prometheus-node-exporter