---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy compiled files
  unarchive:
    src: "/root/project/backend/dist.tar.gz"
    dest: "~/web"

- name: Executing node
  shell: |
    pm2 start ~/web/main.js -f -- start
