---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy compiled files
  unarchive:
    src: "/root/project/backend/dist.tar.gz"
    dest: "~/web"

- name: Copy package.json files
  unarchive:
    src: "/root/project/backend/package.json"
    dest: "~/web"

- name: Install dependencies
  shell: |
    cd ~/web
    npm i

- name: Executing node
  shell: |
    cd ~/web
    pm2 start main.js --name backend
