---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy compiled files
  become: yes
  template:
    src: "~/project/.circleci/ansible/roles/deploy/files/"
    dest: "~/web/"